# Generated by Django 3.2.9 on 2021-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=120)),
                ('module_instructor', models.CharField(max_length=120)),
                ('module_description', models.CharField(max_length=3200)),
                ('module_objectives', models.CharField(max_length=600)),
                ('lesson_num', models.IntegerField()),
                ('lesson_title', models.CharField(max_length=300)),
                ('lesson_subtitle', models.CharField(max_length=300)),
                ('lesson_notes', models.CharField(max_length=3200)),
                ('lesson_image', models.CharField(max_length=300)),
            ],
        ),
    ]
